### ISSUE TITLE
Patch to enable volume buttons

### ISSUE THREAD

**Issue by ghost** [burzumishi/linux-baytrail-flexx10#10]
Patch in this post works for me:  https://lkml.org/lkml/2015/3/31/1087

Power button works out of the box (ie. generates events on press/release, like the volume buttons).  What you do with that is up to you.

**Comment by burzumishi** [comment]
Hi! I've pulled the patch into de repository, thank you! :)

**Comment by burzumishi** [comment]
Working!

**Comment by youling257** [comment]
this patch can be used other z3735f tablet ？ will work on other tablet ?
