### ISSUE TITLE
64bit UEFI

### ISSUE THREAD

**Issue by minipower50** [burzumishi/linux-baytrail-flexx10#18]
Hello
This is not an issue. I did not know another way to contact you.
 The reason for this, is I found 32bit and 64 bit UEFI bios files for Inari tablets. I found both windows 8.1 32bit and 64bit bios files there is also 2 firmware upgrade updater's to go from 32bit to 64 bit and from 64bit to 32bit

The tablet product website
http://www.aavamobile.com/en/products/vertical-devices/28-inari

[Inari 10 bios files.zip](https://github.com/burzumishi/linux-baytrail-flexx10/files/552396/Inari.10.bios.files.zip)

I hope they help getting the nextbook flexx to 64bit UEFI

**Comment by nicman23** [comment]
while interesting and probably very helpful, it is scary to flash uefi for a machine to a not related one :P .
This will most likely help anyone that want to run windows 64, but we can already boot linux 64 without even having to compile anything. 

thanks anyways, will look into this after we got proper sound and power management.
