### ISSUE TITLE
A line in 008-volumes-button.patch is not completed.

### ISSUE THREAD

**Issue by Tuxman2** [burzumishi/linux-baytrail-flexx10#22]
A line in the 008-volumes-button.patch file is not completed.

see it : mp_register_ioapic(ioapic->id, ioapic->address, ioapic->global_irq_base,

Can you tell me if this patch is used to control the buttons available on the screen tablet ?

**Comment by ghost** [comment]
It is complete.  That line is not part of the patch - it's only an alignment reference.  The lines changed are prefixed with "-" or "+" :)

(snip)

+       if (ioapic->global_irq_base < nr_legacy_irqs() ||
+               acpi_gbl_reduced_hardware)
                cfg.type = IOAPIC_DOMAIN_LEGACY;

        mp_register_ioapic(ioapic->id, ioapic->address, ioapic->global_irq_base,
--
1.9.1
