### ISSUE TITLE
Arch on this device

### ISSUE THREAD

**Issue by Haxk20** [burzumishi/linux-baytrail-flexx10#26]
Hi anyone mabaged to go for Arch linux on this device i installed it but after that i installed ubuntu 17.04 back because of that: touchscreen act very weird when i move my finger on desktop it give the selection like thing you know and sometimes its goes off which is good and sometimes its stays on the screen on ubuntu its working awesome even multitouch support without touchegg is there some way to take the ubuntu drivers and configs and other thing and load it into the arch or i should stay at ubuntu ?

**Comment by nicman23** [comment]
Annoy me again in 2 weeks , I ll update the pkgbuilds. They work btw if you don't care about an old kernel. https://github.com/nicman23/misc_aur

**Comment by Haxk20** [comment]
Thanks

**Comment by Haxk20** [comment]
Ok i got Arch working litlle bit better by using jiffies clocksource but it slows down or speed up after sometime so unusable after time and need restart trying to find perfect clocksource but cannot find it

**Comment by nicman23** [comment]
move to #28 and for the pkgbuilds if i ever find the time ~~or the charger...~~ to my repo
