### ISSUE TITLE
Test kernel 4.9.0 on Dell Venue 8 pro & Venue 11 Pro

### ISSUE THREAD

**Issue by Tuxman2** [burzumishi/linux-baytrail-flexx10#27]
Hi everybody,

well, someone tested new kernel 4.9.0 on a tablet machine (see the title). Here is the results and the informations he gives (see link): http://www.studioteabag.com/science/dell-venue-pro-linux/
I don't know if it can help you.

Asus T100T owners talked about an irq8 patch (see this link): https://plus.google.com/102631105919952833656/posts/bH8tmviRViF
Irq8 patch is here: https://drive.google.com/drive/folders/0B4DiU2o72FbuSkpfU0M2LXN5Wk0

**Comment by ghost** [comment]
4.9 upgrade was uneventful on my Flexx 9.  Their IRQ8 (slot 8) fix seems like the same patch to get the volume buttons working.
