### ISSUE TITLE
The resulting kernel is huge! ~ 2.8G

### ISSUE THREAD

**Issue by nicman23** [burzumishi/linux-baytrail-flexx10#3]
We should probably try to slim the .config .... Will try to do this next week.

Basic plan: 1.remove radeonsi, noveau (i flanked french - no idea how new is written)
2.remove non intel powersaving / mobo management / chipset stuff
3.remove any network cards (pci)
4.Hope did nothing to kill everything

Will make a new pull request :)

**Comment by burzumishi** [comment]
Yes you are right! Thank you! 

I've been working on removing pci network cards, non intel chipsets and other stuff.

I'll update a new ".config" using the latest kernel sources, I guess to do it today (I've been a bit busy these week to play with my device). :)

**Comment by nicman23** [comment]
Nice :), btw i wont be able to test anything until after the weekend (irl stuff + do not have my charger :P )

A bit not relevant: there multiple clones of the device we are using. Such as vero w10i, odys wintab 10 and of course flexx10.

I am currently using a vero flashed with odys uefi/bios and should not have too much of an impact... ~~Except maybe the audio card which might be different. You know of any way to get the model?~~

EDIT: after using my google-fu, found my old [driveridentifier ](http://www.driveridentifier.com/scan/desktop.php?scanid=1ECA4881738B42EEBBCE8A3FBA85AEE1) page (for windows i know ugh) that lists the card as realtek \ACPI\10EC5640 focus on the 5640

**Comment by burzumishi** [comment]
Yes you are right, the sound card codec loaded by the kernel is **rt5640** but I've have not any advance on that point, all required sound modules are loaded but I can't see the device listed with "**lspci**".

I've uploaded a configuration script stored in "**sound**" directory.

**Comment by nicman23** [comment]
you would not see it through lspci. It is through sdio and acpi iirc (an interface through sd cards) so it is not a pci device.

**Comment by emelcher** [comment]
To reduce kernel size try:
`make INSTALL_MOD_STRIP=1 -j 4 deb-pkg`

**Comment by burzumishi** [comment]
I'm using "make deb-pkg" instead of "make; make install", this is stripping my kernel build on Debian.

**Comment by nicman23** [comment]
Closing - this is irrelevant as it is the users' concern. He or she should edit the default - distro provided - config to add the needed codecs and drivers for the sound.
