### ISSUE TITLE
Weird problem with tsc

### ISSUE THREAD

**Issue by Haxk20** [burzumishi/linux-baytrail-flexx10#33]
I finally somehow fixed few problems with tsc clocksource still not perfect but better then it was but now i have this problem tsc runs great in gdm or in CLI but not in GUI its laggy and not great at all i cant even watch yt videos on it because its laggy i saw that laggy problem when cpu frequency drop then it lag and when it goes up its ok again but its laggy so much. I thought that you guys should have some idea how to fix this maybe changing something in i915 on in cpu profile or anything else even when you know how to fix it and there is patch post it here i can build kernel and test Thanks.

**Comment by Tuxman2** [comment]
Hi Haxk20,

I would like to know what is tsc and tsc clocksource. Some people put tsc in grub command line. Is there a relationship with c-state, or can be with wifi?

Thanks.

**Comment by Haxk20** [comment]
Tsc is clocksource how cpu ticks and what exactly they put in grub command line ?

**Comment by Haxk20** [comment]
I put tsc=reliable and its again terrible with clocksource=tsc its kinda ok almost but problem with GUI and with reliable wifi is not working cannot find any AP

**Comment by Tuxman2** [comment]
@Haxk20: They put: tsc=reliable force_tsc_stable=1 clocksource=tsc clocksource_failover=tsc
but I don't know if it can solve your problem. Linux Community try to find the solution but it is not easy.

**Comment by Haxk20** [comment]
So im not the only one having problem with tsc ? And what clocksource do you use and what filesystem ?f2fs or ext4 ?

**Comment by Haxk20** [comment]
But weird is that when i use only clocksource=tsc and switch to cli tablet is totally usable no problem but when i use gui its start to do weird stuff so i think problem is with i915 is there some patch for i915 and clocksource maybe like i915 speed or something

**Comment by Haxk20** [comment]
????

**Comment by Haxk20** [comment]
Ok so updated to 4.9.6-ARCH kernel and used those kernel parameters and tadaaa it worked a lot better but wifi is stuck at searching for AP (wifi) with those kernel parameters but when used only clocksource=tsc then wifi worked but not tested other thing if keyboard will do crazy will test and will post here

**Comment by Haxk20** [comment]
Well yeah if only clocksource  = tsc is applied the tablet is unstable again so yeah those parameters are perfect for me from jiffies

**Comment by Haxk20** [comment]
Closing because its fixed with kernel parm.

**Comment by nicman23** [comment]
@Haxk20 to be clear you use all 3 ( `tsc=reliable force_tsc_stable=1 clocksource=tsc clocksource_failover=tsc` ) ?

**Comment by Haxk20** [comment]
Without clocksource=tsc but all others
