### ISSUE TITLE
C-state patch evaluation

### ISSUE THREAD

**Issue by nicman23** [burzumishi/linux-baytrail-flexx10#34]
For me to add in documentation mostly, please ignore (or don't and patch your kernel :P )
https://bugzilla.kernel.org/show_bug.cgi?id=109051

OR 

go with this http://lithops.se/patches-on-4.10rc2.tar.bz2 and remove/ replace the asus things

**Comment by Tuxman2** [comment]
hello nicman23,

I guess we have to wait the kernel 4.10.x to have a good support  for our hardware.
Kernel 4.9.4 is the last for 4.9 series. Is there any patches we must applied from here and elsewhere for this kernel (sound, battery, wifi, ...) ? It will be a good idea to update informations and documentation from here for the new kernels.

Thanks.

**Comment by nicman23** [comment]
c state now stable in upstream (?)

closing
